setup.cfg
src/duplo_resource/lambda.py

List:
```
~/workspaces/kindertales/newktrepos/objectKey-lambda [kindertales]: duploctl lambda list | jq .
[
{
"Architectures": [
"x86_64"
],
"CodeSha256": "2406d0cb772b941acff0ac7f11d77bfe3a0a7aa58434520bb3457e29f87fe9e9",
"CodeSize": 0,
"Description": "Returns AWS Credentials for S3 Upload from Mobile",
"Environment": {
"Variables": {
"PROVIDED_ACCESS_ID": "",
"PROVIDED_SECRET_KEY": ""
}
},
"EphemeralStorage": {
"Size": 512
},
"FileSystemConfigs": [],
"FunctionArn": "arn:aws:lambda:ca-central-1:748544146453:function:duploservices-poc-objectKey-2",
"FunctionName": "duploservices-poc-objectKey-2",
"LastModified": "2023-09-25T17:42:02+00:00",
"Layers": [],
"MemorySize": 512,
"PackageType": {
"Value": "Image"
},
"RevisionId": "534ff533-494d-4768-b91f-f5e1f6022403",
"Role": …
```

adding functionality for lambda management

---

pyproject.toml
src/duplo_resource/cronjob.py
src/duplocloud/client.py

includes fin, list, and update_image

initialized the cronjob resource

---

.github/workflows/test.yml
.gitignore
src/duplo_resource/jit.py
src/duplocloud/argaction.py
src/duplocloud/args.py
src/duplocloud/argtype.py
src/duplocloud/auth.py
src/duplocloud/cli.py
src/duplocloud/client.py
src/duplocloud/commander.py
src/duplocloud/commander_test.py
src/duplocloud/config.py
src/duplocloud/config_test.py
src/duplocloud/errors.py
src/duplocloud/resource.py
src/duplocloud/server.py

This introduces an interactive login flow. This new flow introduced the need for a config class which can figure out how to get all configured prior to building the DuploClient. This also make the config class the owner of all of the global parameters.
Get a list of tenant names as yaml interactive mode.   
```sh
duploctl tenant list -q '[].AccountName' -o yaml --interactive
```
___
enhancement
___
- Introduced a new configuration management system (`DuploConfig`) to handle configurations and interactive login.
- Added global arguments for specifying home directory, cache directory, config file, and enabling interactive login mode.
- Refactored `DuploClient` to utilize `DuploConfig` for configuration, simplifying its implementation.
- Implemented a local server (`TokenServer`) to …

Interactive Login

---

.gitignore
src/duplo_resource/service.py
src/duplocloud/args.py
src/duplocloud/resource.py
src/tests/test_client.py
src/tests/test_commander.py

Adds env var management to services.  Supports merge, replace, and delete.  Merge updates any existing keys with the new value, or adds missing keys.  Replace resets all env vars to the provided vars.  Also fixes a bug in resources.py.
___
___
- Introduced a new feature to manage environment variables in services, including the ability to merge, replace, and delete variables.
- Added necessary command-line arguments in `args.py` to support the new environment variable management feature.
- Fixed a bug in `resource.py` related to tenant retrieval, ensuring the correct tenant configuration is accessed.
___
<tr>
<td>
<details> …

Duplo 14517

---

CONTRIBUTING.md
src/duplo_resource/service.py
src/duplocloud/args.py
src/tests/test_client.py
src/tests/test_commander.py

___
- Introduced a new method `update_replicas` in `service.py` to allow updating the number of replicas for a service.
- Added a new CLI argument `REPLICAS` to specify the number of replicas when using the command line.
- Updated the `CONTRIBUTING.md` with detailed instructions on version bumping, dependency installation, package building, and documentation.
___
<tr>
<td>
<details>
<summary><strong>service.py</strong><dd><code>Add Method to Update Service Replicas</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

add new function in service for updating replicas

---

.github/workflows/installer.yml
.github/workflows/publish.yml
CONTRIBUTING.md
cli.spec
pyproject.toml

Single binary in the making.
___
enhancement
___
- Introduced a GitHub Actions workflow for packaging with Pyinstaller, supporting Windows, Ubuntu, and macOS.
- Updated the publish workflow to include the new Pyinstaller package and adjusted Slack notification dependencies.
- Added build instructions for creating a Pyinstaller binary in CONTRIBUTING.md.
- Created a Pyinstaller spec file for the CLI executable, ensuring necessary modules are included.
- Updated `pyproject.toml` to include Pyinstaller as a build dependency.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>installer.yml</strong><dd><code>Add GitHub Actions Workflow for Pyinstaller …

Pyinstaller Package

---

.github/workflows/installer.yml
.github/workflows/publish.yml

enhancement
___
- Updated GitHub Actions workflow to support publishing releases with PyInstaller artifacts.
- Added inputs to control whether to push the image to the registry.
- Renamed jobs for clarity and added steps to build and publish the installer across different OS versions.
- Introduced a new job for creating GitHub releases with the built artifacts.
- Renamed the Slack notification job to support broader notification mechanisms.
___
<tr>
<td>
<details>
<summary><strong>installer.yml</strong><dd><code>Enhance GitHub Actions Workflow for PyInstaller with Release </code><br><code>Publishing</code></dd></summary>
<hr> …

Pyinstaller

---

.github/workflows/installer.yml
.github/workflows/release.yml

enhancement
___
- Enhanced the GitHub Actions workflow for Pyinstaller to specify operating system and architecture more clearly, supporting `windows`, `linux`, and `darwin` with `amd64` architecture.
- Added architecture information to the artifact names to distinguish between different builds.
- Introduced SHA-256 checksum generation for the release artifacts, improving security and integrity verification of the builds.
___
<tr>
<td>
<details>
<summary><strong>installer.yml</strong><dd><code>Enhance GitHub Actions Workflow for Pyinstaller with OS and </code><br><code>Architecture Specificity</code></dd></summary>
<hr>
.github/workflows/installer.yml …

add checksums and common release names

---

.github/workflows/publish.yml
.github/workflows/test.yml
.github/workflows/test_integration.yml
.github/workflows/test_unit.yml
pyproject.toml
scripts/clean.sh
src/duplo_resource/infrastructure.py
src/duplo_resource/tenant.py
src/duplocloud/args.py
src/duplocloud/client.py
src/duplocloud/resource.py
src/tests/test_client.py
src/tests/test_commander.py
src/tests/test_infra.py
src/tests/test_tenant.py

___
- Introduced a `delete` method for tenant deletion, enhancing the tenant management capabilities.
- Added a `config` method to manage tenant settings, allowing for the addition, update, and deletion of settings.
- Improved argument handling in `args.py` with new arguments for environment variable management and minor formatting changes.
- Implemented a `delete` method in `client.py` to support the deletion of Duplo resources.
___
<tr>
<td>
<details>
<summary><strong>tenant.py</strong><dd><code>Enhancements and New Features in Tenant Management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

config and delete on tenants

---

src/duplo_resource/infrastructure.py
src/duplocloud/errors.py
src/duplocloud/resource.py
src/tests/test_infra.py
src/tests/test_tenant.py

___
- Introduced a new exception `DuploFailedResource` to handle scenarios where a Duplo resource provisioning fails.
- Enhanced error handling in infrastructure provisioning to immediately stop waiting if the provisioning status is failed.
- Updated infrastructure creation test to reflect changes in error handling and to use a different CIDR and region.
- This update improves the robustness of error handling during infrastructure provisioning and testing.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>infrastructure.py</strong><dd><code>Enhanced Error Handling for Infrastructure Provisioning</code>&nbsp; &nbsp; </dd></summary>
<hr> …

Integration tests

---

pyproject.toml
scripts/formula.py
src/duplo_resource/cronjob.py
src/duplo_resource/jit.py
src/duplocloud/args.py
src/duplocloud/client.py
src/duplocloud/resource.py
src/tests/conftest.py
src/tests/data/cronjob.yaml
src/tests/helpers.py
src/tests/test_cronjobs.py
src/tests/test_infra.py
src/tests/test_tenant.py

enhancement
___
- Introduced a new class `DuploTenantResourceV3` to handle V3 resources more effectively, including methods for CRUD operations.
- Refactored `DuploCronJob` class to inherit from `DuploTenantResourceV3`, simplifying the code by removing redundant methods and utilizing inherited ones.
- Minor formatting adjustment in `scripts/formula.py` for code consistency.
- adds admin vs nonadmin k8s credentials in jit process
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting
<tr>
<td>
<details>
<summary><strong>formula.py</strong><dd><code>Minor Indentation Adjustment in Python Script</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

v3 Tenant Resources

---

.gitignore
CONTRIBUTING.md
pyproject.toml
scripts/formula.py
src/duplo_resource/asg.py
src/duplo_resource/hosts.py
src/duplo_resource/lambda.py
src/duplo_resource/tenant.py
src/duplocloud/client.py
src/tests/conftest.py
src/tests/data/asg.yaml
src/tests/data/hosts.yaml
src/tests/data/lambda.yaml
src/tests/data/tenant.yaml
src/tests/test_cronjobs.py
src/tests/test_infra.py
src/tests/test_tenant_resources.py

___
- Implemented CRUD operations for ASG, hosts, and enhanced Lambda management with asynchronous creation and deletion.
- Added error handling for host creation and deletion processes.
- Introduced helper methods for name construction in ASG, hosts, and Lambda modules.
- Improved code readability and safety by adding type hints across test suites and cleaning up documentation.
- Enabled previously commented tests for ASG and hosts to expand the test coverage.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting
</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td>
<details>
<summary><strong>formula.py</strong><dd><code>Improve Variable Assignment Formatting in Formula Script</code>&nbsp; …

crud for asg and hosts

---

pyproject.toml
src/duplo_resource/ecs_service.py
src/duplo_resource/rds.py
src/duplocloud/args.py
src/duplocloud/client.py
src/duplocloud/resource.py
src/tests/conftest.py
src/tests/data/rds-read.yaml
src/tests/data/rds.yaml
src/tests/test_tenant_resources.py

___
- Introduced a comprehensive set of functionalities for managing RDS instances through the new `DuploRDS` class.
- Enhanced argument parsing to support RDS management operations and logging configuration.
- Implemented logging within the `DuploClient` class to facilitate debugging and operational logging.
- Updated test fixtures and data to support RDS resource testing.
- Configuration changes to register the `DuploRDS` class for RDS management.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting
</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td>
<details>
<summary><strong>ecs_service.py</strong><dd><code>Improve Readability in ECS Service Definition</code>&nbsp; &nbsp; &nbsp; …

rds resource and logging (86a2tpr6x)

---

CHANGELOG.md
src/duplo_resource/asg.py
src/duplo_resource/hosts.py
src/duplo_resource/jit.py
src/duplo_resource/job.py
src/duplo_resource/lambda.py
src/duplo_resource/service.py
src/duplo_resource/tenant.py
src/duplocloud/args.py
src/duplocloud/client.py
src/duplocloud/resource.py
src/tests/conftest.py
src/tests/test_jit.py
src/tests/test_tenant.py
src/tests/test_tenant_resources.py

___
- Introduced a new global argument `TENANT_ID` to allow specifying the tenant id, enhancing the flexibility of tenant specification.
- Refactored pod filtering logic in `service.py` to support pods not controlled by a ReplicaSet, fixing a potential bug where such pods were ignored.
- Enhanced `DuploClient` and `DuploTenantResource` classes to support tenant id, improving code maintainability and readability.
___
<tr>
<td>
<details>
<summary><strong>service.py</strong><dd><code>Refactor Pod Filtering Logic for Service Pods</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …

fix azure wait and allow tenant_id global arg

---

.github/actions/setup/action.yml
.github/workflows/docs.yml
mkdocs.yml
pyproject.toml

___
- Configured MkDocs with a material theme and various plugins to enhance the documentation experience.
- Defined a comprehensive navigation structure for the project documentation.
- Added necessary MkDocs dependencies to the project's pyproject.toml.
- Updated the wiki submodule to point to the latest commit.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>mkdocs.yml</strong><dd><code>Setup and Configuration of MkDocs for Project Documentation</code></dd></summary>
<hr>
mkdocs.yml
<li>Configured site name as "Duploctl Wiki".<br> <li> Set documentation directory to "wiki".<br> <li> Applied "material" theme for the …

mkdocs basically working fine

---

CHANGELOG.md
src/duplo_resource/user.py
src/tests/data/create-admin-user.yaml
src/tests/data/create-non-admin-user.yaml
src/tests/data/delete-user.yaml

enhancement, tests
___
- Added support for creating and deleting users, reflected in the CHANGELOG.
- Introduced new test data files for creating an admin user, a non-admin user with extensive properties, and deleting a user.
___
<tr>
<td>
<details>
<summary><strong>CHANGELOG.md</strong><dd><code>Update CHANGELOG for User Management Features</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
CHANGELOG.md
<li>Added entry for support of user creation and deletion in the <br>changelog.<br>
</details>
</td>
<td><a href="https://github.com/duplocloud/duploctl/pull/75/files#diff-06572a96a58dc510037d5ef …

Added support for user creation and deletion

---

src/duplo_resource/jit.py

also added some nice docs
___
___
- Added return type annotations to `aws`, `k8s`, `update_kubeconfig`, `update_aws_config`, and `web` methods in `jit.py`.
- Enhanced docstrings for `aws`, `k8s`, `update_kubeconfig`, `update_aws_config`, and `web` methods with detailed usage examples and return descriptions.
- Modified `update_kubeconfig` method to optionally return the kubeconfig content instead of saving it to a file.
- Improved handling of certificate authority data in Kubernetes context configuration.
- Updated the submodule commit reference in the `wiki` directory.
___
<tr>
<td>
<details> …

fixed kubeconfig command on gcp

---

.github/workflows/pull_request.yml
.github/workflows/test_unit.yml
CHANGELOG.md

enhancement, configuration changes
___
- Added a new GitHub Actions workflow (`pull_request.yml`) to validate pull requests.
- Included a step in the new workflow to ensure changes are logged in `CHANGELOG.md`.
- Integrated unit tests from the existing workflow into the new PR validation workflow.
- Removed the pull request trigger from the existing unit test workflow (`test_unit.yml`) to avoid redundancy.
___
<tr>
<td>
<details>
<summary><strong>pull_request.yml</strong><dd><code>Add PR validation workflow with changelog check and unit tests</code></dd></summary>
<hr>
.github/workflows/pull_request.yml
<li>Added a new GitHub Actions workflow for …

new pr flow

---

CHANGELOG.md
src/duplo_resource/version.py

___
- Added server version retrieval to the version command in `DuploVersion` class.
- Updated the docstring in `DuploVersion` class to include server version information.
- Modified the return structure of the `__call__` method to include `server` version.
- Updated `CHANGELOG.md` to reflect the new feature.
___
<tr>
<td>
<details>
<summary><strong>version.py</strong><dd><code>Add server version retrieval to version command.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/duplo_resource/version.py
<li>Added server version retrieval to the version command.<br> <li> Updated docstring …

server version

---

src/duplo_resource/jit.py

Updated `update_aws_config` function to create a default AWS profile
___
enhancement
___
- Enhanced the `update_aws_config` function to handle cases where the profile name is not provided.
- Added logic to extract the profile name from the `DUPLO_HOST` environment variable if available.
- Set the profile name to "default" if no name is provided or extracted from the environment variable.
___
<tr>
<td>
<details>
<summary><strong>jit.py</strong><dd><code>Enhance `update_aws_config` to handle default profile names</code></dd></summary>
<hr>
src/duplo_resource/jit.py
<li>Added logic to set a default profile name if <code>name</code> is None.<br> <li> …

method update - update_aws_config

---

.dockerignore
.github/workflows/docs.yml
.github/workflows/image.yml
.github/workflows/installer.yml
.github/workflows/package.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.gitignore
CHANGELOG.md
CONTRIBUTING.md
Dockerfile
README.md
docker-compose.yaml
mkdocs.yml
plugins/aws/README.md
plugins/aws/plugin.py
plugins/aws/pyproject.toml
pyproject.toml
src/duplo_resource/tenant.py
src/duplocloud/args.py

includes a client generator and website updater
___
___
- Introduced a new AWS plugin with `DuploAWS` class for AWS service interactions.
- Implemented `client` method for creating AWS clients.
- Added `update_website` command to update S3-hosted websites and invalidate CloudFront cache.
- Added `region` command in tenant resource to get AWS region for a tenant.
- Fixed typo in tenant resource docstring.
- Added `CONTENT_DIR` argument for specifying website content directory.
- Added README documentation for AWS plugin.
- Added project metadata and dependencies for AWS plugin in `pyproject.toml`.
- Updated maintainers list and adjusted dependencies in the main `pyproject.toml`.
___
<table><thead><tr><th></th><th align="left">Relevant …

new aws plugin

---

CHANGELOG.md
pyproject.toml
src/duplo_resource/cloudfront.py
src/duplo_resource/hosts.py

___
- Added a new `CloudFront` resource class in `src/duplo_resource/cloudfront.py` with methods to create, list, disable, and delete CloudFront distributions.
- Updated `CHANGELOG.md` to document the addition of the CloudFront resource.
- Modified `pyproject.toml` to register the CloudFront resource in the project entry points.
___
<tr>
<td>
<details>
<summary><strong>cloudfront.py</strong><dd><code>Add CloudFront resource class with CRUD operations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/duplo_resource/cloudfront.py
<li>Added a new <code>CloudFront</code> resource class.<br> <li> …

added cloudfront resource

---

CHANGELOG.md
src/duplo_resource/service.py

Adds usage example in services.update_env, and slight improvement in services update message
___
Documentation, Enhancement
___
- Added a usage example for the `update_env` command in the `service.py` docstring.
- Improved the success message in the `update_env` command to include the service name.
- Updated the changelog to reflect the new documentation changes for `services.update_env`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>service.py</strong><dd><code>Add usage example and improve success message in `update_env`</code></dd></summary>
<hr>
src/duplo_resource/service.py
<li>Added usage example for <code>update_env</code> command in the …

Doc update

---

CHANGELOG.md
mkdocs.yml
pyproject.toml
src/duplo_resource/plan.py

___
- Added a new resource class `DuploPlan` for managing plans, including methods to list and find plans.
- Implemented error handling for scenarios where a plan is not found.
- Updated `mkdocs.yml` to include documentation entry for the `Plan` resource and corrected paths for `PVC` and `StorageClass`.
- Added an entry point for the `plan` resource in `pyproject.toml`.
___
<tr>
<td>
<details>
<summary><strong>plan.py</strong><dd><code>Add `DuploPlan` resource class with list and find methods</code></dd></summary>
<hr>
src/duplo_resource/plan.py
<li>Added a new resource class <code>DuploPlan</code> for managing plans.<br> <li> …

Plan-resource

---

CHANGELOG.md
mkdocs.yml
pyproject.toml
src/duplo_resource/jit.py
src/duplo_resource/plan.py

___
- Added a new `token` command in `DuploJit` class to retrieve JWT token.
- Introduced a new `DuploPlan` class with `list` and `find` commands for managing plans.
- Updated changelog to reflect the addition of the new plan resource and token command.
- Modified documentation navigation to include Plan and Infrastructure resources.
- Added entry point for `plan` resource in `pyproject.toml`.
___
<tr>
<td>
<details>
<summary><strong>jit.py</strong><dd><code>Add `token` command to retrieve JWT token</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Plan resource

---

CHANGELOG.md
src/duplo_resource/tenant.py

___
- Added a new `dns_config` method in `tenant.py` to retrieve DNS configuration for a tenant by name.
- Updated the changelog to reflect the addition of the tenant DNS config command.
___
<tr>
<td>
<details>
<summary><strong>tenant.py</strong><dd><code>Add `dns_config` method to tenant commands</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/duplo_resource/tenant.py
<li>Added <code>dns_config</code> method to retrieve DNS configuration for a tenant.<br> <li> Included command usage and argument details in the docstring.<br> <li> Returns a …

DUPLO-15739: Added Tenant DNS Config command

---

CHANGELOG.md
src/duplo_resource/service.py
src/duplocloud/resource.py

___
- Enhanced service methods in `service.py` with detailed docstrings and return type annotations.
- Introduced a new `apply` method in `resource.py` to handle both creation and update of resources.
- Updated the changelog to reflect the addition of the `apply` method.
- Updated the wiki submodule reference.
___
<tr>
<td>
<details>
<summary><strong>service.py</strong><dd><code>Enhance service methods with docstrings and return types</code>&nbsp; </dd></summary>
<hr>
src/duplo_resource/service.py
<li>Added detailed docstrings for service methods.<br> <li> Added return type annotations to service methods.<br> <li> Introduced …

apply method and some docs

---

.devcontainer.json
.github/dependabot.yml
.github/workflows/audit.yml
.github/workflows/homebrew.yml
.github/workflows/image.yml
.github/workflows/installer.yml
.gitignore
.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
CHANGELOG.md
CONTRIBUTING.md
Dockerfile
docker-compose.yaml
mkdocs.yml
pyproject.toml
scripts/mkdocs.py
scripts/setup.sh
src/duplo_resource/tenant.py
src/duplo_resource/user.py
src/duplocloud/args.py
src/duplocloud/argtype.py
src/duplocloud/client.py
src/duplocloud/commander.py
src/duplocloud/resource.py
src/tests/test_commander.py

Added devcontainers and vscode setup.
___
Enhancement, Documentation, Tests, Configuration changes
___
- Enhanced MkDocs script with new filters and static file handling.
- Added detailed docstrings and `apply` method for services.
- Introduced command aliases for tenant and user resources.
- Enhanced argument handling and added detailed docstrings.
- Added setup script for environment preparation.
- Added devcontainer configuration for VS Code.
- Added Dependabot configuration for devcontainers.
- Added workflow for auditing dependencies and quality checks.
- Updated Homebrew and image build workflows.
- Added recommended extensions, launch configurations, settings, and tasks for VS Code.
- Updated changelog and contributing guidelines.
- Added devcontainer build stage and updated build …

Usability Improvements

---

CHANGELOG.md
src/duplo_resource/service.py

- [*] Thoroughly reviewed on local machine.

added new service for updating labels in service

---

CHANGELOG.md
src/duplo_resource/service.py

- [*] Thoroughly reviewed on local machine.

Svc label function new

---

CHANGELOG.md
src/duplo_resource/ecs_service.py

Fixed the bug ECS reverting the environment variable, command, secrets

---

CHANGELOG.md
src/duplo_resource/tenant.py

Simply lower case tenant names before comparing.

lower case tenant checks

---

CHANGELOG.md
src/duplo_resource/service.py
src/duplocloud/args.py

Handles cases where existing environment variables are not capitalized, ala Name/Value.  Uses existing standard if defined, and normalizes if no standard is used.  This should minimize impacting existing standards but creates a standard where one does not exist.
https://app.clickup.com/t/8655600/DUPLO-25413
- [ :( ] Have you added any tests

Duplo 25413

---

.vscode/tasks.json
CHANGELOG.md
scripts/runner_install.sh

better way to install the local gha runner

Fancy actions install

---

CHANGELOG.md
src/duplo_resource/job.py

Issue waiting for jobs when pods either have faults or the `Name` key is missing. 
___
Bug fix, Enhancement
___
- Added a new function `check_pod_faults` to handle and raise errors for pod faults during job execution.
- Improved error handling for cases where pods may not have a `Name` key, preventing job wait failures.
- Enhanced the job waiting logic to check for faults and ensure all pod logs are retrieved.
- Updated the changelog to document these fixes and enhancements.
___
<tr>
<td>
<details>
<summary><strong>job.py</strong><dd><code>Improve job waiting logic and error handling for pod faults</code></dd></summary>
<hr>
src/duplo_resource/job.py …

fixed job waiting issues

---

CHANGELOG.md
src/duplo_resource/jit.py

New gcp jit command that retreives a gcp token from the duplo api. 
https://app.clickup.com/t/8655600/DUPLO-15865
___
___
- Introduced a new `gcp` command in `jit.py` to retrieve GCP JWT tokens for authentication with the GCP API.
- Implemented caching mechanism to store and retrieve GCP credentials efficiently.
- Added usage examples for setting environment variables for the `gcloud` CLI.
- Updated `CHANGELOG.md` to document the new GCP JIT command and its usage.
___
<tr>
<td>
<details>
<summary><strong>jit.py</strong><dd><code>Add GCP JWT token retrieval command with caching</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

new gcp jit command

---

CHANGELOG.md
src/duplo_resource/lambda.py

Update the environment variables of a lambda.
https://app.clickup.com/t/8655600/DUPLO-26885
- Noted changes in Changelog.
___
Enhancement
___
- Added a new method `update_env` to update Lambda environment variables.
- Supports merging, replacing, and deleting environment variables.
- Updated `CHANGELOG.md` to document the new feature.
___
<tr>
<td>
<details>
<summary><strong>lambda.py</strong><dd><code>Add `update_env` method for Lambda environment variables</code>&nbsp; </dd></summary>
<hr>
src/duplo_resource/lambda.py
<li>Introduced <code>update_env</code> method for Lambda environment variable updates.<br> <li> …

DUPLO-26885: Update Lambda Environment Variables

---

CHANGELOG.md
src/duplo_resource/service.py
src/duplocloud/args.py

Configure load balancer to a service.
___
Enhancement
___
- Added a new `expose` command to configure load balancers for services.
- Introduced new arguments for load balancer configuration in `args.py`.
- Validated load balancer types and parameters in the `expose` method.
- Enhanced CLI usability with detailed documentation and examples.
___
<tr>
<td>
<details>
<summary><strong>service.py</strong><dd><code>Introduced `expose` method for load balancer configuration</code></dd></summary>
<hr>
src/duplo_resource/service.py
<li>Added a new <code>expose</code> method to configure load balancers.<br> <li> Included validation for load balancer types and …

DUPLO-25387: Configure load balancer to a service

---

CHANGELOG.md
src/duplo_resource/service.py
src/duplocloud/args.py

Add a support for service rollback with a specific revision
https://app.clickup.com/t/8655600/DUPLO-29725
- Make sure to note changes in Changelog

DUPLO-29725: Support for service rollback

---

CHANGELOG.md
src/duplo_resource/service.py
src/duplocloud/args.py

Added enhancement to update_image service to also update the sidecar container image.
https://app.clickup.com/t/8655600/DUPLO-29726
- Make sure to note changes in Changelog

DUPLO-29726: Support sidecar container image update

---

CHANGELOG.md
src/duplo_resource/service.py

Missing key when updating a service. 
https://app.clickup.com/t/8655600/DUPLO-30290

missing agentplatform key

---

CHANGELOG.md
src/tests/test_tenant.py

Added test cases for missing tenant methods, including:
1. list_users
2. billing
3. region
4. dns_config
- Added tests
- Make sure to note changes in Changelog

Added few tests for tenant

---

CHANGELOG.md
src/duplo_resource/asg.py
src/duplocloud/resource.py
src/tests/test_asg.py

Patching support and docs enhancements were added for an ASG.
https://app.clickup.com/t/8655600/DUPLO-30989

DUPLO-30989: Added patching support and docs enhancements for an ASG resource

---

src/duplo_resource/jit.py
src/tests/test_jit.py

Reverts duplocloud/duploctl#169
___
Enhancement
___
- Improved AWS config profile handling to always update profiles
- Added directory creation for non-existent config paths
- Enhanced test coverage with comprehensive integration tests
- Fixed profile update logic and messaging
___
```mermaid
flowchart LR
A["AWS Config Update"] --> B["Check Profile Exists"]
B --> C["Create/Update Profile"]
C --> D["Ensure Directory Exists"]
D --> E["Write Config File"]
E --> F["Return Success Message"]
```
<tr>
<td>
<details>
<summary><strong>jit.py</strong><dd><code>Enhanced AWS config profile update …

Revert "Revert "updated jit update_aws_config""

---

CHANGELOG.md
src/duplo_resource/service.py
src/duplocloud/client.py
src/duplocloud/errors.py
src/duplocloud/resource.py
src/tests/data/service.yaml
src/tests/test_errors.py

Now we can wait for an image to update when there is an HPA present. 
Make a service with hpa enabled in 
https://test24.duplocloud.net/
then one in qa-aws where the old api still exists
then run this in both and watch the logs carefully noticing the differences between DEBUG and INFO. The loglevel set to debug will be much more talkative now. 
```sh
duploctl service update_image duploctl nginx:latest --wait --loglevel DEBUG
```
On the test24 portal, the logs will say it knows the "true count" for the replicas. On qa-aws it will tell you it does not know the "true count" of the replicas. 
For cli
https://app.clickup.com/t/8655600/DUPLO-34549
For backend
https://app.clickup.com/t/8655600/DUPLO-35316
___
Bug fix, Enhancement
___
- Fixed service waiting logic when HPA is enabled
- Added new …

Duplo 34549 updating a service and waiting issue with hpa kelly ferrone

---

CHANGELOG.md
src/duplocloud/client.py
src/duplocloud/server.py

Allow the interactive login to use the redirect login flow which actually works with safari and other browsers. 
Basically allows the interactive login to work with safari. 
First find your cache folder by running
```sh
duploctl
```
Then clear your cache
```sh
rm -rf /path/to/my/cache
```
Then run any command you want with the interactive flag and browser flags
```sh
duploctl system info --interactive --admin --browser safari
```
Selecting accept fully works now and the cli command can finish with a response all using safari. 
Clear your cache again and try with chrome too
```sh
duploctl system info --interactive --admin --browser chrome
```
https://app.clickup.com/t/8655600/DUPLO-30456
___
Enhancement
___
- Enable redirect-based interactive login flow for better browser compatibility
- …

enable redirect based interactive logins

---

CHANGELOG.md
src/duplo_resource/ai.py
src/duplocloud/args.py

DUPLO-33022: Changes to handle optional content/message processing in ticket creation
DUPLO-33022: Changes to handle optional content/message processing in ticket creation
Command with content/message field being passed
Command without content/message
___
Enhancement
___
- Make content parameter optional in ticket creation
- Add conditional message processing flag
- Update return field names for consistency
- Remove validation for AI response field
___
```mermaid
flowchart LR
A["Ticket Creation"] --> B["Content Check"]
B --> C["Content Provided?"]
C -->|Yes| D["Add content & process_message=True"]
C -->|No| E["Skip content processing"]
D --> F["Create Ticket"]
E --> F["Create Ticket"]
F --> G["Return Response"]
``` …

DUPLO-33022: Changes to handle optional content/message processing in ticket creation

---

CHANGELOG.md
src/duplo_resource/service.py

Adds debug logging to wait process and adds additional normalization to image name checking.
https://app.clickup.com/t/8655600/DUPLO-36795
___
Enhancement
___
- Added debug logging to service wait functions
- Enhanced image name normalization for better matching
- Fixed whitespace formatting issues
___
```mermaid
flowchart LR
A["Service Wait Function"] --> B["Debug Logging"]
A --> C["Image Normalization"]
B --> D["Pod Status Tracking"]
C --> E["Remove Docker Prefixes"]
D --> F["Enhanced Wait Monitoring"]
E --> F
```
<tr>
<td>
<details>
<summary><strong>service.py</strong><dd><code>Enhanced service …

adding wait debug logging and additional image normalization logic

---

CHANGELOG.md
src/duplo_resource/asg.py
src/duplocloud/args.py
src/tests/test_asg.py

- Added command `update_allocation_tag` to update allocation tags for an ASG resource.
https://app.clickup.com/t/8655600/DUPLO-36773
___
Enhancement
___
- Added `update_allocation_tag` command for ASG resources
- New command allows updating allocation tags for Auto Scaling Groups
- Added corresponding test coverage and argument definition
- Updated test execution order for proper dependency management
___
```mermaid
flowchart LR
A["ASG Resource"] --> B["update_allocation_tag Command"]
B --> C["UpdateCustomData API"]
D["ALLOCATION_TAG Argument"] --> B
E["Test Coverage"] --> B
```
<tr>
<td>
<details> …

DUPLO-36773: Added command to update allocation tags for an ASG resource

---

CHANGELOG.md
src/duplocloud/client.py
src/tests/test_client.py

- Handles hosts with or without scheme (http/https)
___
Enhancement
___
- Enhanced host sanitization to handle URLs with or without scheme
- Automatically prepends https:// for hosts without scheme prefix
- Improved URL parsing logic for better flexibility
___
```mermaid
flowchart LR
A["Input Host"] --> B{"Has Scheme?"}
B -->|No| C["Prepend https://"]
B -->|Yes| D["Use as-is"]
C --> E["Parse with urlparse"]
D --> E
E --> F["Return https://netloc"]
```
<tr>
<td>
<details>
<summary><strong>client.py</strong><dd><code>Enhanced host sanitization with scheme handling</code>&nbsp; &nbsp; &nbsp; &nbsp; …

Handles hosts with or without scheme (http/https)
