duplocloud/duploctl

- src/duplo_resource/service.py
before pr:
`Traceback (most recent call last):
File "/Users/duplo-matt/.pyenv/versions/3.11.5/bin/duploctl", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/duplo-matt/.pyenv/versions/3.11.5/lib/python3.11/site-packages/duplocloud/cli.py", line 7, in main
out = duplo.run()
^^^^^^^^^^^
File "/Users/duplo-matt/.pyenv/versions/3.11.5/lib/python3.11/site-packages/duplocloud/client.py", line 151, in run
res = svc.exec(command, args)
^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/duplo-matt/.pyenv/versions/3.11.5/lib/python3.11/site-packages/duplocloud/resource.py", line 20, in exec
return command(**vars(parsed_args))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/duplo-matt/.pyenv/versions/3.11.5/lib/python3.11/site-packages/duplo_resource/service.py", line 71, in restart
if res.status_code == 200: …
> response validation moved to client

- .github/workflows/publish.yml
- src/duplocloud/args.py
- src/duplocloud/config.py
found issue when setting tenant
___
___
- Updated the `TENANT` argument in `src/duplocloud/args.py` to fetch its default value from an environment variable, improving flexibility.
- Removed the duplicate `TENANT` argument definition in `src/duplocloud/args.py`, cleaning up the code.
- Modified the default tenant value in `DuploConfig` constructor to `None` to ensure environment variables are used by default.
- Enhanced the GitHub Actions workflow in `.github/workflows/publish.yml` by specifying job dependencies, ensuring proper execution order.
___
<tr>
<td>
<details>
<summary><strong>args.py</strong><dd><code>Refactor TENANT …
> default tenant to none so env var is used

- src/duplo_resource/jit.py
- src/duplocloud/config.py
___
- Introduced expiration handling for AWS and Kubernetes credentials caching to ensure freshness of cached credentials.
- Enhanced cache key generation for Kubernetes credentials to be more specific by including `planId`.
- Added new methods in `config.py` to support expiration checks and dynamic expiration time calculation for cached items.
- Improved cache management by refining cache key generation and utilizing expiration handling for better cache validity.
___
<tr>
<td>
<details>
<summary><strong>jit.py</strong><dd><code>Enhance Credentials Caching with Expiration Handling for AWS and …
> k8s and aws caches creds now too

- src/duplo_resource/jit.py
- src/duplocloud/config.py
also open aws console in browser ;)
Run this to make a profile
```sh
duploctl jit update_aws_config qa-aws --interactive
```
Try it out with this:  
```sh
aws s3 ls --profile qa-aws
```
You can do this: 
```sh
duploctl jit update_kubeconfig --plan test01 --ctx qa-aws  
```
then run this to check that it works
```sh
kubectl get nodes
```
```sh
duploctl jit web --ctx qa-aws
```
___
___
- Added support for bypassing cache when retrieving AWS session credentials.
- Fixed format issues with AWS credentials and Kubernetes credentials by removing problematic fields.
- Introduced a new command to update AWS CLI configuration with JIT credentials.
- Implemented functionality to open AWS console in the browser directly from the command line.
- Enhanced command construction to …
> aws and k8s config fun

- .github/workflows/release.yml
enhancement
___
- Added a manual trigger option to allow running the release workflow manually for debugging purposes.
- Simplified the release message generation process by removing the separate step and integrating the message directly into the asset upload step.
- By default, releases are now marked as final (not prerelease).
- Improved job summary to include detailed release information, including tag, release URL, Docker, and PyPi details.
___
<tr>
<td>
<details>
<summary><strong>release.yml</strong><dd><code>Enhance Release Workflow and Simplify Release Message Generation</code></dd></summary>
<hr>
.github/workflows/release.yml
<li>Added manual …
> let it run manually to debug

- .github/workflows/image.yml
- .github/workflows/test.yml
- installer.spec
- src/duplo_resource/jit.py
- src/duplocloud/client.py
enhancement
___
- Enhanced Kubernetes configuration handling in `jit.py` to conditionally include `certificate-authority-data` or `insecure-skip-tls-verify` based on the `K8Provider` value.
- Fixed an issue in `client.py` where the cache key generation could include slashes from the host URL, potentially leading to incorrect cache keys.
___
<tr>
<td>
<details>
<summary><strong>jit.py</strong><dd><code>Enhance Kubernetes Configuration Handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/duplo_resource/jit.py
<li>Refactored <code>__k8s_exec_credential</code> …
> fixed issues with aks jit

- src/duplo_resource/jit.py
enhancement
___
- Corrected the formatting of expiration timestamps for AWS CLI and Kubernetes credentials to ensure compatibility.
- Introduced `datetime` usage for handling timezone-aware datetime objects, improving the reliability of timestamp formatting.
- Enhanced the `aws` method to correctly format the expiration timestamp as expected by AWS CLI.
- Updated the `__k8s_exec_credential` method to format the expiration timestamp correctly for Kubernetes credentials.
___
<tr>
<td>
<details>
<summary><strong>jit.py</strong><dd><code>Correct Expiration Timestamp Formatting for AWS CLI and Kubernetes </code><br><code>Credentials</code></dd></summary>
<hr> …
> expiration format issue fix

- CHANGELOG.md
- src/duplo_resource/user.py
- src/tests/data/user.yaml
Adds functionality to remove users from tenants.  Removes tenant arg to prevent CLI confusion on desired tenant.  Adds example user yaml file.
```
~/workspaces/sureswift-parsers/docparser-infrastructure [docparser]: !665
duploctl user add_user_to_tenant nobody@duplocloud.net --tenant testing
"User 'nobody@duplocloud.net' added to tenant 'testing'"
~/workspaces/sureswift-parsers/docparser-infrastructure [docparser]: duploctl user remove_user_from_tenant nobody@duplocloud.net --tenant testing
"User 'nobody@duplocloud.net' removed from tenant 'testing'"
```
> removing tenant arg, adding remove_user_from_tenant

- CHANGELOG.md
- src/duplocloud/client.py
small change to client __call__ to avoid raw TypeErrors and such
___
enhancement, error handling
___
- Enhanced error handling in the `__call__` method of the client to provide more informative error messages.
- Added a try-except block to catch `TypeError` and print the resource's docstring if available.
- Included traceback printing for cases where no docstring is found.
___
<tr>
<td>
<details>
<summary><strong>client.py</strong><dd><code>Improve client error handling with detailed messages</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/duplocloud/client.py
<li>Added <code>traceback</code> import.<br> <li> Wrapped resource call in …
> update client error handling to print docstrings on error

- CHANGELOG.md
- src/duplo_resource/tenant.py
- src/duplo_resource/user.py
Moves add/remove user from tenant
adds command to list users by tenant
```
(.venv) ~/workspaces/duplocloud/duploctl [salesdemo]: duploctl tenant list_users --tenant dev01  | jq .
[
{
"Username": "test",
"IsReadOnly": "True",
"IsAdmin": "False"
},
{
"Username": "aaron@duplocloud.net",
"IsReadOnly": "False",
"IsAdmin": "True"
}
]
```
```
(.venv) ~/workspaces/duplocloud/duploctl [salesdemo]: duploctl tenant add_user test --tenant compliance
"User 'test' added to tenant 'compliance'"
~/workspaces/duplocloud/duploctl [salesdemo]: duploctl tenant list_users --tenant compliance | jq .
[
{
"Username": "test",
"IsReadOnly": "False",
"IsAdmin": "False"
},
{
"Username": "aaron@duplocloud.net",
"IsReadOnly": "False",
"IsAdmin": "True"
}
]
```
```
(.venv) ~/workspaces/duplocloud/duploctl [salesdemo]: …
```
> Duplo 20526

- CHANGELOG.md
- Dockerfile
- docker-compose.yaml
- scripts/setup.sh
- src/duplo_resource/configmap.py
- src/duplo_resource/secret.py
- src/duplocloud/args.py
- src/duplocloud/argtype.py
- src/tests/files/password.txt
- src/tests/test_commander.py
Configmaps and secrets can be created `--from-file` or `--from-literal` just like kubectl does. It even includes the `--dry-run` option.
> configmaps and secrets from files and literals

- .devcontainer.json
- CHANGELOG.md
- src/duplo_resource/service.py
Fix issue with otherDockerconfig getting erased on updates. 
https://app.clickup.com/t/8655600/DUPLO-21004
___
Bug fix, Enhancement
___
- Fixed an issue where `OtherDockerConfig` was being erased during updates by ensuring it is copied from `Template` to the main body in `service.py`.
- Enhanced the development container configuration by adding a default Python interpreter path in `.devcontainer.json`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>service.py</strong><dd><code>Fix and ensure persistence of `OtherDockerConfig` during updates</code></dd></summary>
<hr>
src/duplo_resource/service.py
<li>Ensure <code>OtherDockerConfig</code> is copied from …
> copy up other docker config

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- src/duplo_resource/cronjob.py
- src/tests/test_cronjobs.py
- Added logic to CronJob Update to set `isAnyHostAllowed`. We need to explicitly set this because of the choices made in the API design. Fixing the underlying problem would require making changes to our UI, Backend, and Terraform and deploying hotfixes to customers. 
[DUPLO-25186](https://app.clickup.com/t/8655600/DUPLO-25186)
> DUPLO-25186: Add logic to set IsAnyHostAllowed

- CHANGELOG.md
- src/duplo_resource/service.py
When updating an image and the image was the same as before two issues would occur: 
- last deployed by who and when did not get reported
- the wait flag would cause an error because a certain value wasn't initialized properly. 
https://app.clickup.com/t/8655600/DUPLO-25663
https://app.clickup.com/t/8655600/DUPLO-25221
> update image issues

- CHANGELOG.md
- src/duplo_resource/jit.py
- src/duplocloud/client.py
see changelog
https://app.clickup.com/t/8655600/DUPLO-25862
> Kubeconfig Updater

- CHANGELOG.md
- src/duplo_resource/version.py
more duplo components in version
> More Component Versions

- CHANGELOG.md
- docker-compose.yaml
Build fix by removing any potential cyclic dependencies in docker-compose.yaml.
[DUPLO-26299](https://app.clickup.com/t/8655600/DUPLO-26299)
Related: [docker/compose 12235](https://github.com/docker/compose/issues/12235#issuecomment-2445030390)
___
___
- Removed potential cyclic dependencies in `docker-compose.yaml` by explicitly defining inherited sections.
- Updated `docker-compose.yaml` to include specific image tags and build arguments.
- Added environment variables for the `duploctl-bin` service.
- Updated `CHANGELOG.md` to reflect the changes made in the `docker-compose.yaml`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details> …
> DUPLO-26299 Build fix

- CHANGELOG.md
- src/duplo_resource/service.py
Added --wait flag for Service Start, Stop and Restart
https://app.clickup.com/t/8655600/DUPLO-21449
- Make sure to note changes in Changelog.
___
Enhancement
___
- Added `--wait` flag for service start, stop, and restart commands.
- Updated `restart`, `stop`, and `start` methods to handle `wait` flag.
- Enhanced CLI commands to optionally wait for service updates.
- Updated changelog to reflect new `--wait` flag feature.
___
<tr>
<td>
<details>
<summary><strong>service.py</strong><dd><code>Add `wait` flag support to service methods</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> DUPLO-21449: Added --wait flag for Service Start, Stop and Restart

- CHANGELOG.md
- src/duplocloud/cli.py
Added a generic exception block to handle any unexpected errors that are not instances of DuploError, improving overall robustness.
https://app.clickup.com/t/8655600/DUPLO-30344
- Make sure to note changes in Changelog
> DUPLO-30344: Added generic exception block

- CHANGELOG.md
- src/duplo_resource/service.py
While executing bulk_update_image duploctl getting an error: An unexpected error occurred: 'list' object has no attribute 'items'. Issue was `serviceimage` arg is a list of lists, not a dictionary so calling .items() on it results in an error.
https://app.clickup.com/t/8655600/DUPLO-31078
> DUPLO-31078: IssueFix bulk_update_image was not working

- CHANGELOG.md
- src/duplo_resource/ingress.py
- src/tests/test_ingress.py
- Patching support and docs enhancements were added for an Ingress. 
- Follwoing usecases are tested -
```
duploctl ingress create -f src/tests/data/ingress.yaml
duploctl ingress update duploctl-ingress -f src/tests/data/ingress.yaml 
duploctl ingress update duploctl-ingress --replace lbConfig.dnsPrefix test
duploctl ingress update duploctl-ingress --replace rules/0.port 8080
duploctl ingress update duploctl-ingress --remove lbConfig.dnsPrefix
duploctl ingress update duploctl-ingress --remove rules.0
duploctl ingress update duploctl-ingress --add data.ExistingKey
duploctl ingress update duploctl-ingress --add rules/- <json>
duploctl ingress delete duploctl-ingress
```
https://app.clickup.com/t/8655600/DUPLO-30983
> DUPLO-30983: Added patching support and docs enhancements for an Ingress resource

- CHANGELOG.md
- src/duplo_resource/cloudfront.py
- src/duplo_resource/ecs_service.py
- src/duplo_resource/hosts.py
- src/duplo_resource/infrastructure.py
- src/duplo_resource/job.py
- src/duplo_resource/rds.py
- src/duplo_resource/service.py
- src/duplocloud/errors.py
- src/duplocloud/resource.py
- src/tests/test_errors.py
Added DuploStillWaitingResource exception to handle cases where a Duplo resource remains in a waiting state. 
https://app.clickup.com/t/8655600/DUPLO-30803
> DUPLO-30803: Added DuploStillWaiting class for resource waiting state

- CHANGELOG.md
- src/duplo_resource/asg.py
- src/duplo_resource/aws_secret.py
- src/duplo_resource/cloudfront.py
- src/duplo_resource/ecs_service.py
- src/duplo_resource/hosts.py
- src/duplo_resource/infrastructure.py
- src/duplo_resource/job.py
- src/duplo_resource/lambda.py
- src/duplo_resource/rds.py
- src/duplo_resource/service.py
- src/duplo_resource/ssm_param.py
- src/duplo_resource/tenant.py
- src/duplocloud/args.py
- src/duplocloud/client.py
- src/duplocloud/resource.py
- src/tests/test_asg.py
- src/tests/test_aws_secret.py
- src/tests/test_cloudfront.py
- src/tests/test_hosts.py
- src/tests/test_service.py
- src/tests/test_service_update_image.py
Added a timeout parameter to the service update_image to control operation duration.
https://app.clickup.com/t/8655600/DUPLO-31178
> DUPLO-31178: Add wait flag as global parameter to duplo client

- CHANGELOG.md
- src/duplo_resource/batch_definition.py
Duplocloud returns 0 for vcpu and memory in the containerproperties object.  If you attempt to submit this, it fails.  The existing implementation deletes these values on submit.
However, customers may specify actual vcpu and memory values in the containerproperties object (deprecated) instead of the resourceRequirements array (preferred).  In these cases, we were deleting the vcpu and memory settings and the update was failing because vcpu and memory are required.
This PR checks to ensure vpcu and memory are present in the existing ResourceRequirements array before deleting the values in containerProperties. This is further complicated by duplocloud issue DUPLO-34396 in which the resourceRequirements array is returned incorrectly from a GET request.  To deal with this, the def …
> Batch Job Def fixes for deprecated vcpu/memory assignment

- CHANGELOG.md
- src/duplo_resource/jit.py
- src/tests/test_jit.py
Updated the logic to always overwrite the specified AWS profile in the config file with new values, ensuring consistent configuration updates instead of skipping existing profiles.
https://app.clickup.com/t/8655600/DUPLO-34392
___
Enhancement
___
- Modified AWS profile configuration to always overwrite existing profiles
- Added comprehensive test coverage for profile creation and updates
- Updated changelog to document the behavior change
___
```mermaid
flowchart LR
A["AWS Config Check"] --> B["Profile Exists?"]
B --> C["Create/Update Profile"]
C --> D["Write Config File"]
D --> E["Return Success Message"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><t …
> DUPLO-34392: Updated duploctl jit update_aws_config to overwrite existing profile

- CHANGELOG.md
- src/duplo_resource/batch_definition.py
After updating job definitions with duploctl, customer reported:
An error occurred (ClientException) when calling the SubmitJob operation: Job with shareIdentifier or schedulingPriority can onlybe submitted to job queue with fair share scheduling policy.
This was caused by the job definition GET returning schedulingpriority with a 0 value.  This PR removes it if set to zero.  It's worth noting that 0 is a valid value, but ultimately that's a backend issue.
https://app.clickup.com/t/8655600/DUPLO-35318
___
Bug fix
___
- Remove zero-value `SchedulingPriority` from batch job definitions
- Prevent submission errors to non-prioritized job queues
- Update changelog with fix details
___
```mermaid
flowchart LR
A["Job Definition GET"] --> B["Contains SchedulingPriority: 0"]
B --> C["Remove …
```
> removing schedulingpriority if set to 0

- src/duplo_resource/jit.py
- src/tests/test_jit.py
This reverts commit ecb0cf3f688b7f4b49c6debd94eb03a2f9aa932e.
___
Bug fix
___
- Reverted AWS config update logic to prevent profile overwriting
- Removed comprehensive test coverage for config file operations
- Simplified profile existence checking mechanism
- Eliminated directory creation functionality
___
```mermaid
flowchart LR
A["Original AWS Config Logic"] --> B["Reverted Implementation"]
C["Comprehensive Tests"] --> D["Basic Tests Only"]
B --> E["Profile Overwrite Prevention"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>jit.py</strong><dd><code>Revert AWS config profile update logic</code>&nbsp; …
> Revert "updated jit update_aws_config"

- CHANGELOG.md
- src/duplo_resource/ecs_service.py
- src/tests/test_ecs_service.py
- updates find_def to first look up input service name's family name, then uses it to look up task def
This pull request fixes an issue with how ECS task definitions are looked up when updating service images, ensuring the correct task definition family is used even when the service name and task definition family differ. It also adds a unit test to verify this behavior.
Bug fix for ECS service image updates:
* Updated `find_def` in `src/duplo_resource/ecs_service.py` to use the `TaskDefFamily` from the service endpoint, ensuring the correct task definition is found when the service name and task definition family are different.
Testing improvements:
* Added a new unit test `test_find_def_uses_taskdef_family_from_service` in `src/tests/test_ecs_service.py` to verify that `find_def` uses …
> DUPLO-35823 feat(ecs): update find def to use service family name

- CHANGELOG.md
- src/duplo_resource/aws_secret.py
- src/duplocloud/args.py
- src/duplocloud/client.py
- src/duplocloud/commander.py
- src/duplocloud/formats.py
- Updated some spelling errors in error messages and doc strings
https://app.clickup.com/t/8655600/DUPLO-36861
___
Documentation
___
- Fixed spelling errors in AWS Secrets Manager docstrings
- Corrected error messages for better clarity
- Updated argument descriptions for consistency
- Added changelog entry for documentation improvements
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>aws_secret.py</strong><dd><code>AWS Secrets Manager spelling corrections</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> DUPLO-36861: Spelling errors in error messages and doc strings

- CHANGELOG.md
- src/duplo_resource/asg.py
- src/tests/test_asg.py
DUPLO-37215 Allow min or max setting on ASG to be zero (0) by checking for None instead of falsey values which treats zero (0) as false.
https://app.clickup.com/t/8655600/DUPLO-37215
___
Bug fix
___
- Fixed ASG scale command to accept zero values
- Changed falsey value checks to explicit None checks
- Added comprehensive tests for zero value scenarios
___
```mermaid
flowchart LR
A["ASG scale method"] --> B["Check parameters"]
B --> C["Previous: falsey check"]
B --> D["Fixed: None check"]
C --> E["Zero treated as false"]
D --> F["Zero allowed as valid"]
F --> G["Update ASG configuration"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td> …
> DUPLO-37215 Allow min or max setting on ASG to be zero (0)
